# app/ports.py
from typing import List, Dict, Protocol, Tuple, Optional

class EmbedderPort(Protocol):
    def embed_texts(self, texts: List[str]) -> List[List[float]]: ...
    def embed_query(self, text: str) -> List[float]: ...

class VectorStorePort(Protocol):
    def add(self, ids: List[str], vectors: List[List[float]], metadatas: List[Dict]): ...
    def query(self, query_vector: List[float], k: int) -> List[Dict]: ...

class RerankerPort(Protocol):
    def rerank(self, query: str, hits: List[Dict]) -> List[Dict]: ...

class LLMPort(Protocol):
    def chat(self, system: str, user: str, temperature: float, max_tokens: int) -> Tuple[str, Dict]: ...

class ParserPort(Protocol):
    def parse_pdf(self, path: str) -> Dict: ...
