run_name: "crdc_ingest_2022_2025"
years: [2020, 2021, 2022, 2023, 2024, 2025]

seed_urls:
  - "https://www.insidecotton.com/categories/2020-final-reports"
  - "https://www.insidecotton.com/categories/2021-final-reports"
  - "https://www.insidecotton.com/categories/2022-final-reports"
  - "https://www.insidecotton.com/categories/2023-final-reports"
  - "https://www.insidecotton.com/categories/2024-final-reports"
  - "https://www.insidecotton.com/categories/2025-final-reports"
  
include_patterns:
  - "\\.pdf$"
  - "(?i)final\\s*report"

exclude_patterns:
  - "(?i)newsletter"
  - "(?i)flyer"
  - "(?i)poster"

timeout_secs: 20
concurrency: 4
retry:
  attempts: 3
  backoff_secs: 2

output:
  jsonl: "data/staging/docs.jsonl"
  csv:   "data/staging/docs.csv"
download_dir: "data/raw"
user_agent: "CRDC-Knowledge-Hub-Ingest-QUT/0.1"

