# configs/runtime.yaml
embedder:
  adapter: bge_local
  model: BAAI/bge-small-en-v1.5

vector_store:
  adapter: faiss_local
  path: data/embeddings/vectors.faiss
  ids:  data/embeddings/ids.npy
  meta: data/staging/chunks.jsonl

reranker:
  adapter: bge_reranker         # or "none" if you haven’t added the adapter file yet
  model: BAAI/bge-reranker-base

llm:
  adapter: ollama               # "openai" if you actually want to pay
  model: llama3.1               # or mistral, qwen2.5, phi3, etc.
  temperature: 0.2
  max_output_tokens: 800
